# defalut

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/connection?serverTimezone=UTC&characterEncoding=UTF-8
    password: 1234
    username: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /api
  port: 8080
  address: 0.0.0.0